version: '3'

services:
  a4c:
    image: alien4cloud/alien4cloud
    container_name: a4c
    networks: 
      - frontend
    ports: 
      - "8088:8088"


networks: 
  frontend:
    driver: bridge

  backend:
    driver: bridge
