version: '3'

services:
  im:
    image: grycap/im:1.9.1  # <-- This is the im container version
    container_name: im
    env_file:
        - "im/im.env"
    volumes:
      - ./im/etc/im:/etc/im
      - ./im/db:/db
    ports:
      - "8800:8800" # <-- API port is map to 8800
    network_mode: "bridge"
  im-web:
    image: grycap/im-web
    depends_on: 
      - im
    container_name: im-web
    env_file:
      - "./im-web/im-web.env"
    volumes:
      - ./im-web/db:/home/www-data
    ports: 
      - "80:80"
    links:
      - im:im grycap/im-web
    network_mode: "bridge"
