version: '3'

services:
  a4c:
    container_name: a4c
    image: indigodatacloud/alien4cloud-deep:2.0-r0
    env_file:
      - .env
    ports:
            - '8080:8080'
    volumes:
      - ./data:/data
      - /etc/ssl:/certs:ro


